### PR TITLE
fix #90

### LINKED ISSUE #90: Fix the Supine table for Latin
Branched from #82 
Per @monzug We need to fix the Supine table:

SUPINE
accusative -um
ablative -ū

no stem, no conjugation, no singular or plural, no active or passive. this is the supine.

### PR DESCRIPTION
**Pull request by balmas**
Per @monzug request, it is better to have a single column for all conjugations. I figured out the right way to do this... I think.

### CODE REVIEW

**Comment by balmas** [comment]
ok @kirlat I will take a look and see about reworking this.

**Comment by balmas** [comment]
Ok @kirlat here's a version which is built on your branch #infltbl-i76. It's definitely simpler this way :-)

I'm not sure if your infltbl-i76 is ready for merge yet or not? It is working for my table, but the verb-supine-irregular table is not getting populated

**Comment by kirlat** [comment]
I'm waiting for Monica to test `infltbl-i76` so I wouldn't say it can be merged now. I'll check the verb-supine-irregular table issue.

**Comment by monzug** [comment]
ops, sorry guys to hold you on something. Kirlat, I will test infltbl-i76
which it looks like it has been already downloaded.

**Comment by monzug** [comment]
I just checked and I did comment on issue #76. there are some open issues
that we need to discuss I believe.

**Pull request merged**
